<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Imports -->
    <xacro:include filename="wheels.xacro" />

    <!-- Parameters -->
    <xacro:property name="chassis_width" value="0.43" />
    <xacro:property name="chassis_length" value="0.55" />
    <xacro:property name="chassis_height" value="0.25" />
    <xacro:property name="chassis_X_offset" value="-0.1" />
    <xacro:property name="chassis_Z_offset" value="0.08" />
    <xacro:property name="drive_wheels_Y_spacing" value="0.46" />
    <xacro:property name="caster_wheels_F_Y_spacing" value="0.52" />
    <xacro:property name="caster_wheels_R_Y_spacing" value="0.405" />
    <xacro:property name="caster_wheels_F_X_offset" value="0.35" />
    <xacro:property name="caster_wheels_R_X_offset" value="-0.4" />
    
    <!-- Material declaration --> 
    <material name="plastic_shell">
        <color rgba="0 0 1 1" />
    </material>

    <!-- Base link -->
    <link name="base_link"></link>

    <!-- Chassis -->
    <link name="chassis">
    <visual>
        <origin xyz="0 0 0"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="plastic_shell"/>
    </visual>
    </link>

    <joint name="chassis_joint" type="fixed">  
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${chassis_X_offset} 0 ${chassis_height/2 - drive_wheel_radius + chassis_Z_offset}"/>
    </joint>
    
    <!-- Drive Wheels -->
    <xacro:drive_wheel name="drive_wheel_L"></xacro:drive_wheel>

    <joint name="drive_wheel_joint_L" type="continuous">
        <parent link="base_link"/>
        <child link="drive_wheel_L"/>
        <origin xyz="0 ${drive_wheels_Y_spacing/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:drive_wheel name="drive_wheel_R"></xacro:drive_wheel>

    <joint name="drive_wheel_joint_R" type="continuous">
        <parent link="base_link"/>
        <child link="drive_wheel_R"/>
        <origin xyz="0 -${drive_wheels_Y_spacing/2} 0" rpy="${pi} 0 0" />
        <axis xyz="0 -1 0"/>
    </joint>

    <!-- Caster Wheels -->
    <xacro:caster_wheel name="caster_wheel_FL"></xacro:caster_wheel>

    <joint name="caster_wheel_joint_FL" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_FL"/>
        <origin xyz="${caster_wheels_F_X_offset} ${caster_wheels_F_Y_spacing/2} ${-drive_wheel_radius + caster_wheel_radius + caster_wheel_Z_offset}" rpy="0 0 0" />
    </joint>

    <xacro:caster_wheel name="caster_wheel_FR"></xacro:caster_wheel>

    <joint name="caster_wheel_joint_FR" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_FR"/>
        <origin xyz="${caster_wheels_F_X_offset} -${caster_wheels_F_Y_spacing/2} ${-drive_wheel_radius + caster_wheel_radius + caster_wheel_Z_offset}" rpy="0 0 0" />
    </joint>

    <xacro:caster_wheel name="caster_wheel_RL"></xacro:caster_wheel>

    <joint name="caster_wheel_joint_RL" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_RL"/>
        <origin xyz="${caster_wheels_R_X_offset} ${caster_wheels_R_Y_spacing/2} ${-drive_wheel_radius + caster_wheel_radius + caster_wheel_Z_offset}" rpy="0 0 0" />
    </joint>

    <xacro:caster_wheel name="caster_wheel_RR"></xacro:caster_wheel>

    <joint name="caster_wheel_joint_RR" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_RR"/>
        <origin xyz="${caster_wheels_R_X_offset} -${caster_wheels_R_Y_spacing/2} ${-drive_wheel_radius + caster_wheel_radius + caster_wheel_Z_offset}" rpy="0 0 0" />
    </joint>
</robot>
