<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Parameters -->
    <xacro:property name="drive_wheel_radius" value="0.17" /> <!-- TODO: Calibrate Drive wheel radius -->
    <xacro:property name="drive_wheel_thickness" value="0.075" />
    <xacro:property name="caster_wheel_radius" value="0.075" /> <!-- TODO: Calibrate Drive wheel radius -->
    <xacro:property name="caster_wheel_thickness" value="0.05" />
    <xacro:property name="caster_wheel_X_offset" value="0.05" />
    <xacro:property name="caster_wheel_Z_offset" value="0.09" />

    <!-- Material declaration -->
    <material name="wheel_rubber">
        <color rgba="0.8 0.8 0.8 1" />
    </material>
    
    <!-- Macros -->
    <!-- Drive Wheels -->
    <xacro:macro name="drive_wheel" params="name">
        <link name="${name}">
            <visual>
                <origin xyz="0 ${drive_wheel_thickness/2} 0" rpy="-${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${drive_wheel_radius}" length="${drive_wheel_thickness}" />
                </geometry>
                <material name="wheel_rubber" />
            </visual>
        </link>
    </xacro:macro>       

    <!-- Caster Wheels --> 
    <xacro:macro name="caster_wheel" params="name">
        <link name="${name}">
            <visual>
                <origin xyz="-${caster_wheel_X_offset} 0 -${caster_wheel_Z_offset}" rpy="-${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_thickness}"/>
                </geometry>
                <material name="wheel_rubber" />
            </visual>
        </link>
    </xacro:macro>       
</robot>
